class Locale:
    ReceivedAnswer = "Received answer: "
    Total = "\n\nFinally: "
    DoesntHaveMandatory = "Source code is invalid or some tests were failed. Read the task more carefully! Please retry."
    NotInFunctional = "Source code is not in functional style. Please retry. Only one language operator is allowed."
    HaveRestricted = "Source code may contain restricted values or functions. Please retry."
    Failed = "Failed"
    Timeout = "Timeout on the next test."
    GeneralError = "An unknown error was found, please contact your supervisor."
    Passed = "Passed"
    EasyModeHelp = "\nA wrong answer was received for the input:\n%s"
    CrashFound = "\nProgram crash found in your reply:\n"
    YourAnswer = "\nYour answer is: \n"
    Test = "Test"