if __name__ == "__main__":
    print("Test #4")
    jsonSerializer = JsonSerializer()

    jsonSerializer.beginArray()
    jsonSerializer.addArrayItem("0")
    jsonSerializer.beginArray()
    jsonSerializer.endArray()
    jsonSerializer.beginArray()
    jsonSerializer.addArrayItem("1")
    jsonSerializer.addArrayItem("2")
    jsonSerializer.endArray()
    jsonSerializer.beginArray()
    jsonSerializer.addArrayItem("3")
    jsonSerializer.addArrayItem("4")
    jsonSerializer.endArray()
    jsonSerializer.beginArray()
    jsonSerializer.addArrayItem("5")
    jsonSerializer.endArray()
    jsonSerializer.endArray()